-- Varsa eskiyi sil
local oldGui = game.CoreGui:FindFirstChild("DevDeneme")
if oldGui then oldGui:Destroy() end

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "DevDeneme"
screenGui.Parent = game.CoreGui

local textLabel = Instance.new("TextLabel")
textLabel.Parent = screenGui
textLabel.BackgroundTransparency = 1 -- Arka planı tamamen kaldırdım
textLabel.AnchorPoint = Vector2.new(0.5, 0.5) -- Tam merkezleme
textLabel.Position = UDim2.new(0.5, 0, 0.5, 0) 
textLabel.Size = UDim2.new(1, 0, 1, 0) -- Tüm ekranı kaplayan görünmez alan

-- Yazı Ayarları
textLabel.Text = "MAL BUNYAMIN RATI YEDİN"
textLabel.TextColor3 = Color3.fromRGB(255, 0, 0) -- Parlak Kırmızı
textLabel.TextSize = 200 -- Dev boyut (Ekrana sığmazsa aşağıdan TextScaled açılır)
textLabel.Font = Enum.Font.RobotoLTC_Black -- En kalın fontlardan biri
textLabel.RichText = true -- Daha kaliteli görünüm için
textLabel.TextStrokeTransparency = 0 -- Yazı etrafına siyah çerçeve (okunabilirliği artırır)
textLabel.TextStrokeColor3 = Color3.new(0, 0, 0)

print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
print("RATTED RATTED")
