local Player = game:GetService("Players").LocalPlayer
local PPS = game:GetService("ProximityPromptService")
local UIS = game:GetService("UserInputService")


local function CreateUI()
    local UI_Target = Player:WaitForChild("PlayerGui")
    if UI_Target:FindFirstChild("wraith") then UI_Target.wraith:Destroy() end

    local sg = Instance.new("ScreenGui", UI_Target)
    sg.Name = "wraith"
    sg.ResetOnSpawn = false

    local MainFrame = Instance.new("Frame", sg)
    MainFrame.Size = UDim2.new(0, 220, 0, 50)
    MainFrame.Position = UDim2.new(0.5, -110, 0, 40)
    MainFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    MainFrame.BorderSizePixel = 0
    Instance.new("UICorner", MainFrame)

    local Title = Instance.new("TextLabel", MainFrame)
    Title.Size = UDim2.new(1, 0, 1, 0)
    Title.BackgroundTransparency = 1
    Title.Text = "quick event [f]"
    Title.TextColor3 = Color3.fromRGB(255, 60, 60)
    Title.Font = Enum.Font.GothamBold
    Title.TextSize = 14

    local Stroke = Instance.new("UIStroke", MainFrame)
    Stroke.Thickness = 2
    Stroke.Color = Title.TextColor3

    return Title, Stroke
end

local StatusLabel, Stroke = CreateUI()
local IsActive = false


local function InstantAction(prompt)
    if IsActive then
        prompt.HoldDuration = 0
        prompt.RequiresLineOfSight = false
        task.spawn(function()
            if fireproximityprompt then
                fireproximityprompt(prompt)
            end
            prompt:InputHoldBegin()
            task.defer(function() prompt:InputHoldEnd() end)
        end)
    end
end


UIS.InputBegan:Connect(function(input, gpe)
    if not gpe and input.KeyCode == Enum.KeyCode.F then
        IsActive = not IsActive
        StatusLabel.Text = IsActive and "quick event [on]" or "quick event [off]"
        local Color = IsActive and Color3.fromRGB(0, 255, 150) or Color3.fromRGB(255, 60, 60)
        StatusLabel.TextColor3 = Color
        Stroke.Color = Color
    end
end)


PPS.PromptButtonHoldBegan:Connect(InstantAction)
PPS.PromptShown:Connect(function(p) 
    if IsActive then p.HoldDuration = 0 p.RequiresLineOfSight = false end 
end)


Player.Character.Humanoid.WalkSpeed = 25 

print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")
print("wraith executed")